<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SuperAdmin\DashboardController;
use App\Http\Controllers\SuperAdmin\LaporanController;
use App\Http\Controllers\SuperAdmin\ManajemenTokoController;
use App\Http\Controllers\SuperAdmin\RiwayatAktivitasController;
use App\Http\Controllers\SuperAdmin\KomisiGlobalController;
use App\Http\Controllers\SuperAdmin\ModerasiProdukController;
use App\Http\Controllers\SuperAdmin\ManajemenPenggunaController;
use App\Http\Controllers\SuperAdmin\PermintaanPenarikanController;
use App\Http\Controllers\SuperAdmin\DataBankController;
use App\Http\Controllers\SuperAdmin\DataPesananController;
use App\Http\Controllers\SuperAdmin\DataPembayaranController;
use App\Http\Controllers\SuperAdmin\PengembalianDanaController;
use App\Http\Controllers\SuperAdmin\PaketSlotProdukController;
use App\Http\Controllers\SuperAdmin\PengaturanSistemController;
use App\Http\Controllers\SuperAdmin\ProfilController;
use App\Http\Controllers\SuperAdmin\KategoriProdukController;
use App\Http\Controllers\SuperAdmin\KurirController;
use App\Http\Controllers\SuperAdmin\PajakBiayaController;
use App\Http\Controllers\SuperAdmin\PromoPlatformController;
use App\Http\Controllers\SuperAdmin\KomplainController as SaKomplainController;
use App\Http\Controllers\SuperAdmin\PengirimanController as SaPengirimanController;
use App\Http\Controllers\SuperAdmin\StokController as SaStokController;
use App\Http\Controllers\SuperAdmin\ProduksiController;
use App\Http\Controllers\SuperAdmin\GudangController;
use App\Http\Controllers\SuperAdmin\SaldoTokoController;
use App\Http\Controllers\SuperAdmin\ProdukController;
use App\Http\Controllers\Admin\DashboardOperasionalController;
use App\Http\Controllers\Admin\DataPesananController as AdminDataPesananController;
use App\Http\Controllers\Admin\VerifikasiPembayaranController;
use App\Http\Controllers\Admin\DataCustomerController;
use App\Http\Controllers\Admin\DataProdukController;
use App\Http\Controllers\Admin\StokController;
use App\Http\Controllers\Admin\PengirimanController;
use App\Http\Controllers\Admin\PengembalianDanaController as AdminPengembalianDanaController;
use App\Http\Controllers\Admin\KomplainController;
use App\Http\Controllers\Admin\PromoController;
use App\Http\Controllers\Admin\PermintaanProduksiController;
use App\Http\Controllers\Admin\KoordinasiGudangController;
use App\Http\Controllers\Admin\ProfilController as AdminProfilController;
use App\Http\Controllers\Admin\LaporanController as AdminLaporanController;
use App\Http\Controllers\Admin\RiwayatAktivitasController as AdminRiwayatAktivitasController;
use App\Http\Controllers\Gudang\DashboardController as GudangDashboardController;
use App\Http\Controllers\Gudang\StokController as GudangStokController;
use App\Http\Controllers\Gudang\BarangMasukController as GudangBarangMasukController;
use App\Http\Controllers\Gudang\BarangKeluarController as GudangBarangKeluarController;
use App\Http\Controllers\Gudang\PemindahanStokController as GudangPemindahanStokController;
use App\Http\Controllers\Gudang\PemeriksaanStokController as GudangPemeriksaanStokController;
use App\Http\Controllers\Gudang\StokRusakController as GudangStokRusakController;
use App\Http\Controllers\Gudang\RiwayatStokController as GudangRiwayatStokController;
use App\Http\Controllers\Gudang\NotifikasiController as GudangNotifikasiController;
use App\Http\Controllers\Gudang\ProfilController as GudangProfilController;
use App\Http\Controllers\Owner\DashboardController as OwnerDashboardController;
use App\Http\Controllers\Owner\DataTokoController;
use App\Http\Controllers\Owner\PengajuanTokoController;
use App\Http\Controllers\Owner\PengaturanTokoController;
use App\Http\Controllers\Owner\ProdukController as OwnerProdukController;
use App\Http\Controllers\Owner\ModerasiProdukController as OwnerModerasiProdukController;
use App\Http\Controllers\Owner\PaketSlotController;
use App\Http\Controllers\Owner\PesananController as OwnerPesananController;
use App\Http\Controllers\Owner\PromoController as OwnerPromoController;
use App\Http\Controllers\Owner\UlasanController;
use App\Http\Controllers\Owner\ProduksiController as OwnerProduksiController;
use App\Http\Controllers\Owner\GudangController as OwnerGudangController;
use App\Http\Controllers\Owner\PengirimanController as OwnerPengirimanController;
use App\Http\Controllers\Owner\SaldoController;
use App\Http\Controllers\Owner\PencairanDanaController;
use App\Http\Controllers\Owner\PengembalianDanaController as OwnerPengembalianDanaController;
use App\Http\Controllers\Owner\KomplainController as OwnerKomplainController;
use App\Http\Controllers\Owner\KaryawanController;
use App\Http\Controllers\Owner\LaporanController as OwnerLaporanController;
use App\Http\Controllers\Owner\NotifikasiController as OwnerNotifikasiController;
use App\Http\Controllers\Owner\ProfilController as OwnerProfilController;

Route::get('/', function () {
    return view('welcome');
});

Route::prefix('superadmin')->name('superadmin.')->group(function () {
    Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');
    Route::get('/manajemen-pengguna', [ManajemenPenggunaController::class, 'index'])->name('manajemen-pengguna');
    Route::get('/manajemen-toko', [ManajemenTokoController::class, 'index'])->name('manajemen-toko');
    Route::get('/moderasi-produk', [ModerasiProdukController::class, 'index'])->name('moderasi-produk');
    Route::get('/kategori-produk', [KategoriProdukController::class, 'index'])->name('kategori-produk');
    Route::get('/paket-slot-produk', [PaketSlotProdukController::class, 'index'])->name('paket-slot-produk');
    Route::get('/data-pesanan', [DataPesananController::class, 'index'])->name('data-pesanan');
    Route::get('/data-pembayaran', [DataPembayaranController::class, 'index'])->name('data-pembayaran');
    Route::get('/pengembalian-dana', [PengembalianDanaController::class, 'index'])->name('pengembalian-dana');
    Route::get('/permintaan-penarikan', [PermintaanPenarikanController::class, 'index'])->name('permintaan-penarikan');
    Route::get('/komisi-global', [KomisiGlobalController::class, 'index'])->name('komisi-global');
    Route::get('/pajak-biaya', [PajakBiayaController::class, 'index'])->name('pajak-biaya');
    Route::get('/promo-platform', [PromoPlatformController::class, 'index'])->name('promo-platform');
    Route::get('/data-bank', [DataBankController::class, 'index'])->name('data-bank');
    Route::get('/kurir', [KurirController::class, 'index'])->name('kurir');
    Route::get('/laporan', [LaporanController::class, 'index'])->name('laporan');
    Route::get('/riwayat-aktivitas', [RiwayatAktivitasController::class, 'index'])->name('riwayat-aktivitas');
    Route::get('/pengaturan-sistem', [PengaturanSistemController::class, 'index'])->name('pengaturan-sistem');
    Route::get('/profil', [ProfilController::class, 'index'])->name('profil');
    Route::get('/komplain', [SaKomplainController::class, 'index'])->name('komplain');
    Route::get('/pengiriman', [SaPengirimanController::class, 'index'])->name('pengiriman');
    Route::get('/stok', [SaStokController::class, 'index'])->name('stok');
    Route::get('/produksi', [ProduksiController::class, 'index'])->name('produksi');
    Route::get('/gudang', [GudangController::class, 'index'])->name('gudang');
    Route::get('/saldo-toko', [SaldoTokoController::class, 'index'])->name('saldo-toko');
    Route::get('/produk', [ProdukController::class, 'index'])->name('produk');
});

Route::prefix('admin')->name('admin.')->group(function () {
    Route::get('/dashboard', [DashboardOperasionalController::class, 'index'])->name('dashboard');
    Route::get('/pesanan', [AdminDataPesananController::class, 'index'])->name('pesanan');
    Route::get('/verifikasi-pembayaran', [VerifikasiPembayaranController::class, 'index'])->name('verifikasi-pembayaran');
    Route::get('/customer', [DataCustomerController::class, 'index'])->name('customer');
    Route::get('/produk', [DataProdukController::class, 'index'])->name('produk');
    Route::get('/stok', [StokController::class, 'index'])->name('stok');
    Route::get('/pengiriman', [PengirimanController::class, 'index'])->name('pengiriman');
    Route::get('/pengembalian-dana', [AdminPengembalianDanaController::class, 'index'])->name('pengembalian-dana');
    Route::get('/komplain', [KomplainController::class, 'index'])->name('komplain');
    Route::get('/promo', [PromoController::class, 'index'])->name('promo');
    Route::get('/permintaan-produksi', [PermintaanProduksiController::class, 'index'])->name('permintaan-produksi');
    Route::get('/koordinasi-gudang', [KoordinasiGudangController::class, 'index'])->name('koordinasi-gudang');
    Route::get('/profil', [AdminProfilController::class, 'index'])->name('profil');
    Route::get('/laporan', [AdminLaporanController::class, 'index'])->name('laporan');
    Route::get('/riwayat-aktivitas', [AdminRiwayatAktivitasController::class, 'index'])->name('riwayat-aktivitas');
});

Route::prefix('gudang')->name('gudang.')->group(function () {
    Route::get('/dashboard', [GudangDashboardController::class, 'index'])->name('dashboard');
    Route::get('/stok', [GudangStokController::class, 'index'])->name('stok');
    Route::get('/barang-masuk', [GudangBarangMasukController::class, 'index'])->name('barang-masuk');
    Route::get('/barang-keluar', [GudangBarangKeluarController::class, 'index'])->name('barang-keluar');
    Route::get('/pemindahan', [GudangPemindahanStokController::class, 'index'])->name('pemindahan');
    Route::get('/pemeriksaan', [GudangPemeriksaanStokController::class, 'index'])->name('pemeriksaan');
    Route::get('/stok-rusak', [GudangStokRusakController::class, 'index'])->name('stok-rusak');
    Route::get('/riwayat-stok', [GudangRiwayatStokController::class, 'index'])->name('riwayat-stok');
    Route::get('/notifikasi', [GudangNotifikasiController::class, 'index'])->name('notifikasi');
    Route::get('/profil', [GudangProfilController::class, 'index'])->name('profil');
});

Route::prefix('owner')->name('owner.')->group(function () {
    Route::get('/dashboard', [OwnerDashboardController::class, 'index'])->name('dashboard');
    Route::get('/data-toko', [DataTokoController::class, 'index'])->name('data-toko');
    Route::get('/pengajuan-toko', [PengajuanTokoController::class, 'index'])->name('pengajuan-toko');
    Route::get('/pengaturan-toko', [PengaturanTokoController::class, 'index'])->name('pengaturan-toko');
    Route::get('/produk', [OwnerProdukController::class, 'index'])->name('produk');
    Route::get('/moderasi-produk', [OwnerModerasiProdukController::class, 'index'])->name('moderasi-produk');
    Route::get('/paket-slot', [PaketSlotController::class, 'index'])->name('paket-slot');
    Route::get('/pesanan', [OwnerPesananController::class, 'index'])->name('pesanan');
    Route::get('/promo', [OwnerPromoController::class, 'index'])->name('promo');
    Route::get('/ulasan', [UlasanController::class, 'index'])->name('ulasan');
    Route::get('/produksi', [OwnerProduksiController::class, 'index'])->name('produksi');
    Route::get('/gudang', [OwnerGudangController::class, 'index'])->name('gudang');
    Route::get('/pengiriman', [OwnerPengirimanController::class, 'index'])->name('pengiriman');
    Route::get('/saldo', [SaldoController::class, 'index'])->name('saldo');
    Route::get('/pencairan-dana', [PencairanDanaController::class, 'index'])->name('pencairan-dana');
    Route::get('/pengembalian-dana', [OwnerPengembalianDanaController::class, 'index'])->name('pengembalian-dana');
    Route::get('/komplain', [OwnerKomplainController::class, 'index'])->name('komplain');
    Route::get('/karyawan', [KaryawanController::class, 'index'])->name('karyawan');
    Route::get('/laporan', [OwnerLaporanController::class, 'index'])->name('laporan');
    Route::get('/notifikasi', [OwnerNotifikasiController::class, 'index'])->name('notifikasi');
    Route::get('/profil', [OwnerProfilController::class, 'index'])->name('profil');
});
